package com.heuristix.guns.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

// Date: 3/3/2013 11:49:47 AM
// Teplate version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
public class ModelRocket extends ModelBase {

	// fields
	private ModelRenderer shape1;
	private ModelRenderer shape2;
	private ModelRenderer shape3;

	public ModelRocket() {
		textureWidth = 64;
		textureHeight = 32;

		shape1 = new ModelRenderer(this, 0, 0);
		shape1.addBox(0F, 0F, 0F, 1, 3, 1);
		shape1.setRotationPoint(0F, 0F, 0F);
		shape1.setTextureSize(64, 32);
		shape1.mirror = true;
		setRotation(shape1, 0F, 0F, 1.570796F);
		shape2 = new ModelRenderer(this, 0, 0);
		shape2.addBox(0F, 0F, 0F, 1, 2, 1);
		shape2.setRotationPoint(0F, 1F, 0F);
		shape2.setTextureSize(64, 32);
		shape2.mirror = true;
		setRotation(shape2, 0F, 0F, 4.712389F);
		shape3 = new ModelRenderer(this, 0, 0);
		shape3.addBox(0F, -1F, 0F, 1, 2, 1);
		shape3.setRotationPoint(-3F, 1F, 0F);
		shape3.setTextureSize(64, 32);
		shape3.mirror = true;
		setRotation(shape3, 0F, 0F, 4.712389F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		shape1.render(f5);
		shape2.render(f5);
		shape3.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}


}
